package:
  name: biom-format
  version: !!str 2.1.2

source:
  fn: biom-format-2.1.2.tar.gz
  url: https://pypi.python.org/packages/source/b/biom-format/biom-format-2.1.2.tar.gz
  md5: 94aaaec7af71ff1c074306b4cde87022

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.3.0
    - pyqi ==0.3.2
    - scipy >=0.13.0

  run:
    - python
    - setuptools
    - numpy >=1.3.0
    - pyqi ==0.3.2
    - scipy >=0.13.0

test:
  # Python imports
  imports:
    - biom

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - biom convert --version

about:
  home: http://www.biom-format.org
  license:  BSD License
  summary: 'Biological Observation Matrix (BIOM) format'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
