package:
  name: burrito
  version: !!str 0.9.0

source:
  fn: burrito-0.9.0.tar.gz
  url: https://pypi.python.org/packages/source/b/burrito/burrito-0.9.0.tar.gz
  md5: 0f7899fc72c5c3c643fdb1daf8f5202b

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - future

test:
  # Python imports
  imports:
    - burrito
    - burrito.tests

about:
  home: https://github.com/biocore/burrito
  license:  BSD License
  summary: 'Framework for wrapping and controlling command-line applications.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
