package:
  name: pynast
  version: !!str 1.2.2

source:
  fn: pynast-1.2.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pynast/pynast-1.2.2.tar.gz
  md5: 6f1744d8d3f333eb2dbe81026d4dcb1b

requirements:
  build:
    - python
    - numpy >=1.5.1
    - cogent >=1.5.3

  run:
    - python
    - numpy >=1.5.1
    - cogent >=1.5.3

test:
  # Python imports
  imports:
    - pynast

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://qiime.org/pynast
  license:  BSD License
  summary: 'The Python Nearest Alignment Space Termination tool'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
